# Generated by Django 2.2.12 on 2020-08-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_scpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='bigintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='booleanfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='charfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='datefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='datetimefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='decimalfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='durationfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='emailfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='floatfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='genericipaddressfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='imagefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='integerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='nullbooleanfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='positiveintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='positivesmallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='slugfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='smallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='textfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='timefield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='opsscpagespage',
            name='uuidfield',
        ),
    ]
