# Generated by Django 2.2.12 on 2020-07-31 23:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pipelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='bigintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='booleanfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='charfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='datefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='datetimefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='decimalfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='durationfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='emailfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='floatfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='genericipaddressfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='imagefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='integerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='nullbooleanfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='positiveintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='positivesmallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='slugfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='smallintegerfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='textfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='timefield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='opspipelinespage',
            name='uuidfield',
        ),
        migrations.AlterField(
            model_name='opspipelinespage',
            name='sections',
            field=wagtail.core.fields.StreamField([('S_PipelineBlock', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name of the presentator', null=True, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='Important! Format https://www.domain.tld/xyz', null=True, required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Other information', null=True, required=False)), ('activity_log', wagtail.core.blocks.StreamBlock([('activity', wagtail.core.blocks.StructBlock([('datetime', wagtail.core.blocks.DateTimeBlock(null=True, required=True))], blank=False, icon='fa-calendar-check-o', null=True))], blank=False, null=True)), ('verified', wagtail.core.blocks.BooleanBlock(default=False, help_text='Whether the attendee was attending or not', null=False, required=False)), ('token', wagtail.core.blocks.CharBlock())], icon='cogs', null=True))], null=True),
        ),
    ]
