name: Python CI tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Lint with flake8
              run: |
                  pip install flake8
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 esite --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 esite --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Check imports sort order
              run: |
                  pip install isort
                  isort --check-only --diff --recursive esite
            - name: Build static files
              run: |
                  cd ./esite/static_src
                  npm install
                  npm run build:prod
